version: '3'
services:
  backend:
    build:
      context: "./"
      dockerfile: "Dockerfile-backend"
    volumes:
      - ".:/app"
    ports:
      - "4567:4567"
    depends_on:
      - frontend
  frontend:
    build:
      context: "./"
      dockerfile: "Dockerfile-frontend"
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
