FROM ruby:2.6.3-alpine
ENV APP_ROOT /app
WORKDIR $APP_ROOT

COPY Gemfile .
RUN gem install bundler
RUN bundle install && bundle clean

COPY ./pages/index.rb $APP_ROOT
EXPOSE 4567

CMD ruby pages/index.rb -o 0.0.0.0
